version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-risiko-lokal
    container_name: form_risk_app
    restart: unless-stopped
    environment:
      - PORT=80
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=form_risk_db
      - DB_USERNAME=root
      - DB_PASSWORD=bpr_password_rahasia
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://34.50.94.222.nip.io
      - APP_KEY=base64:HNC5hVhAuN9zhi4x2SjiTgo1uIdGS905s5LvquZBeqg=
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: form_risk_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=form_risk_db
      - MYSQL_ROOT_PASSWORD=bpr_password_rahasia
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from 34.50.94.222.nip.io --to app:80
    depends_on:
      - app

volumes:
  db_data:
