version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-risiko-lokal
    container_name: form_risk_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: form_risk_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=form_risk_db
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from 34.50.94.222.nip.io --to app:80
    depends_on:
      - app

volumes:
  db_data:
